// AUTOGENERATED SHIM — real source moved to packages/core/src/inferrer/play-format
// TODO: 逐步把 tests/*.ts 的 import 换到 "@site2source/core/..." 然后删除这些 shim。
export * from "../packages/core/src/inferrer/play-format";
