#!/usr/bin/env node
/**
 * gen-spider.mjs — 用 @site2source/core 生成 spider.js + tvbox 片段
 *
 * 用法: node scripts/gen-spider.mjs <site-name>
 *
 * 输入: packages/core/src/sites/<name>.ts 需要 export makeXxxModel() 或 XXX_MODEL
 * 输出:
 *   test-output/spider_<name>.js
 *   test-output/tvbox_<name>.json  (只含本 site 的片段, 供发布器用)
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "../../..");

const name = process.argv[2];
if (!name) {
  console.error("用法: node scripts/gen-spider.mjs <site-name>");
  process.exit(1);
}

// 加载 .env (给 makeXxxModel 提供 secret)
const envPath = path.join(REPO, ".env");
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/);
    if (m && !process.env[m[1]]) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
    }
  }
}

// 动态 import 站点定义
const siteFile = path.join(REPO, "packages/core/src/sites", `${name}.ts`);
if (!fs.existsSync(siteFile)) {
  console.error(`❌ 找不到 ${siteFile}`);
  console.error("   先创建站点定义: packages/core/src/sites/<name>.ts");
  console.error("   模板: cp packages/core/src/sites/aiyifan.ts packages/core/src/sites/<name>.ts");
  process.exit(2);
}

const siteMod = await import(pathToFileURL(siteFile).href);
const factoryName = `make${name[0].toUpperCase()}${name.slice(1)}Model`;
const constName = `${name.toUpperCase()}_MODEL`;

let model;
if (typeof siteMod[factoryName] === "function") {
  // 优先用 factory (让它读环境变量)
  model = siteMod[factoryName]({ withProxy: !!process.env[`${name.toUpperCase()}_PROXY_TOKEN`] });
  console.log(`使用 ${factoryName}()${model.proxy ? " with proxy" : ""}`);
} else if (siteMod[constName]) {
  model = siteMod[constName];
  console.log(`使用 ${constName} (无 factory)`);
} else {
  console.error(`❌ ${siteFile} 必须 export ${factoryName}() 或 ${constName}`);
  process.exit(3);
}

// 导入 generator
const { generateT3SpiderFromModel } = await import(
  pathToFileURL(path.join(REPO, "packages/core/src/generators/t3-spider.ts")).href
);

const spiderSrc = generateT3SpiderFromModel(model);

// 输出
const outDir = path.join(REPO, "test-output");
fs.mkdirSync(outDir, { recursive: true });
const spiderPath = path.join(outDir, `spider_${name}.js`);
fs.writeFileSync(spiderPath, spiderSrc);
console.log(`spider ${spiderSrc.length} bytes -> ${spiderPath}`);

// tvbox 片段
const tvboxFragment = {
  key: `${name}`,
  name: model.display_name || model.name,
  type: 3,
  api: `./sites/${name}/spider.js`, // 相对 tvbox 仓库根
  searchable: 1,
  quickSearch: 1,
  filterable: 1,
  categories: (model.categories || []).map((c) => c.name),
  source: model.site_url,
  note: `Generated by site2source from packages/core/src/sites/${name}.ts`,
};
const tvboxPath = path.join(outDir, `tvbox_${name}.json`);
fs.writeFileSync(tvboxPath, JSON.stringify(tvboxFragment, null, 2));
console.log(`tvbox fragment -> ${tvboxPath}`);

// P0 检查: flags 数组不能含 site 自家 key
if (Array.isArray(model.flags) && model.flags.includes(name)) {
  console.error(`\n🔴 P0 pitfall: model.flags 包含 "${name}"`);
  console.error("   FongMi 会报 'Unable to parse url'. 从 model.flags 移除 site key.");
  process.exit(4);
}

console.log("\n✅ 生成完成, 下一步:");
console.log(`   node ${path.relative(process.cwd(), path.join(__dirname, "verify-spider.mjs"))} ${name}`);
